tasks:
  - init: >-
      curl -fsSL https://deno.land/x/install/install.sh | sh &&
      /home/gitpod/.deno/bin/deno completions bash > /home/gitpod/.bashrc.d/90-deno && 
      echo 'export DENO_INSTALL="/home/gitpod/.deno"' >> /home/gitpod/.bashrc.d/90-deno && 
      echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> /home/gitpod/.bashrc.d/90-deno
vscode:
  extensions:
    - denoland.vscode-deno@3.2.0:5307ff8c1db475f21d402d09ac4a6bb3